title = "Kiln"

[window]
dim_w = 1920
dim_h = 1080

[window.renderer]
vsync = true
hwaccel = true

[assets]
[assets.imgfmt]
jpg = true
png = true
tif = true
webp = true

[assets.audio]

[logs]
level = 2